<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container62NxMWL\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container62NxMWL/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container62NxMWL.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container62NxMWL\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container62NxMWL\srcDevDebugProjectContainer(array(
    'container.build_hash' => '62NxMWL',
    'container.build_id' => 'fd842938',
    'container.build_time' => 1543251710,
), __DIR__.\DIRECTORY_SEPARATOR.'Container62NxMWL');
